language: node_js
node_js:
  - node
jobs:
  include:
    - stage: Deploy
      if: branch = master
      cache: npm
      script:
        - npm i
        - gridsome build
      deploy:
        provider: pages
        local_dir: dist/
        target-branch: gh-pages
        name: Travis Deployment Bot
        skip_cleanup: true
        github_token: "$GITHUB_TOKEN"
        fqdn: openmeetings.jbhutch.com
        on:
          branch: master
notifications:
  email: false
env:
  global:
    secure: WclJqL/Rku68VHYcPg9hI9VxFm3AI02OYXJFHQl97IgPwIwMmfMmgKBTX78bmYkV0fvXkLZvxSNyNaZSYaINmIuaBPviRGzCi/3ZNjYV++oQx1iYACxqjPo4m+X0aC0XnE4sjxXfVxnJW9Z6NT/2gHGs1UqLzPf47l4d0Ku6ehS2oTBiqciOd8RNGpQvjmPAN++lebXiuaEMMcLxBpYSHMopyEDP3eZUU9xqtBMUJkfUaB36XK3VZYEh4hooaRoxEnBq4U3YuWx6dO6KNHRonCyg6aZTp1xjiwQSzGIcmRB3suEB9jZUsaqGwLdNK0KGQJ8hbYXDzTKs4ElQ8o4sqxnLi+6/RqGQJTTqrpIq5c4VRF2GLZ3tYIE60IY+eHAvOtIm/DrHfo3xLD4OuV/10puUbltom1EjOuATBUzUeK3NglB+D8kq/dYczrwBMPHG+Mc/jesflaYF/Rkhot0wclW7yWaPbHl484OF4th6jftQuGrnUPSAS0EmaD6UaC3UsUC9MxMbYT6oEhDaJIyoJ+GBHPwBz2cKqL2gYEe4w1zfaevCcwL7j7C6EpkJJsoQW5t7Ro4Ln8rRNA7T2JlfEN8r3SJJgd2VIGbR1jtpxrlv4cbQlutyyLe3U3Ii0aQYfiSoNsAByLlkcP1/EdBkrWzguoCfMrsoIe3Al7fDHNU=
