name: Scrape & Rebuild

on:
  schedule:
    - cron:  '0 8 * * *'

  workflow_dispatch:

jobs:
    # Job named "scrape"
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install Scrapy
        run: pip install scrapy

      - name: Fetch latest data
        run: |-
          scrapy runspider scraper/spiders/meetingScraper.py --nolog -o - > ./data/meetings.json

      - name: Commit and push if it changed
        run: |-
          git config user.name "🤖 Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
