name: Scrape Data

on:
  schedule:
    - cron:  '0 8 * * *'

  workflow_dispatch:

jobs:
  build:
    name: Scrape Data
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install Scrapy
        run: pip install scrapy

      - name: Fetch latest data
        run: scrapy runspider scraper/spiders/meetingScraper.py --loglevel=INFO -O ./data/index.json

      - name: Commit changes
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: data
          FOLDER: data
          COMMIT_MESSAGE: "Update data"
          CLEAN: true
